/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Col1Layout: typeof import('./src/components/layout/Col1Layout.vue')['default']
    Col2Layout: typeof import('./src/components/layout/Col2Layout.vue')['default']
    CompleteMessageContainer: typeof import('./src/components/layout/CompleteMessageContainer.vue')['default']
    ConfirmContainer: typeof import('./src/components/layout/ConfirmContainer.vue')['default']
    DataContainerMountedMask: typeof import('./src/components/layout/DataContainerMountedMask.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExternalLinksGroup: typeof import('./src/components/profile/ExternalLinksGroup.vue')['default']
    IconMenuBox: typeof import('./src/components/layout/IconMenuBox.vue')['default']
    IECControlBox: typeof import('./src/components/image/image-edit/components/IECControlBox.vue')['default']
    IECPostList: typeof import('./src/components/image/image-edit/components/IECPostList.vue')['default']
    ImageEditCard: typeof import('./src/components/image/image-edit/ImageEditCard.vue')['default']
    ImageEditDialog: typeof import('./src/components/image/image-edit/ImageEditDialog.vue')['default']
    ImageGroup: typeof import('./src/components/image/ImageGroup.vue')['default']
    ImageSelector: typeof import('./src/components/image/ImageSelector.vue')['default']
    PageFooter: typeof import('./src/components/layout/PageFooter.vue')['default']
    PostCard: typeof import('./src/components/post/PostCard.vue')['default']
    PostGroup: typeof import('./src/components/post/PostGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialMediasGroup: typeof import('./src/components/profile/SocialMediasGroup.vue')['default']
    TestBox: typeof import('./src/components/TestBox.vue')['default']
    TextWithLink: typeof import('./src/components/post/TextWithLink.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    TweetEmpty: typeof import('./src/components/layout/TweetEmpty.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
